import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Outfit, Bricolage_Grotesque } from "next/font/google";
import { Providers } from "./providers";

// Font files can be colocated inside of `pages`
const satoshiFont = localFont({ src: "./fonts/Satoshi-Variable.woff2" });

const bricolageFont = Bricolage_Grotesque({ subsets: ["latin"] });
const outfitFont = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anurag Deore Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfitFont.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
